/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Property, Agent, JournalPost, Testimonial, FAQItem, Milestone, StatsBlock } from './types';

export const agents: Agent[] = [
  {
    id: 'A01',
    name: 'AMIT SHARMA',
    role: 'CHIEF ACQUISITIONS OFFICER',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400&h=400',
    phone: '+91 98200 12345',
    email: 'amit.sharma@saiproperties.com',
    bio: 'WITH OVER 15 YEARS OF TRANSACTION EXPERIENCE IN PREMIUM METROPOLITAN MARKETS, AMIT HEADS PORTFOLIO ACQUISITIONS AND HIGH-VALUE COMMERCIAL LEASING WITH MATHEMATICAL RIGOR.'
  },
  {
    id: 'A02',
    name: 'PRIYA MEHTA',
    role: 'HEAD OF RESIDENTIAL SALES',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400&h=400',
    phone: '+91 98200 67890',
    email: 'priya.mehta@saiproperties.com',
    bio: 'PRIYA SPECIALIZES IN LUXURY PENTHOUSES AND ASYMMETRIC APARTMENT PORTFOLIOS. HER REPUTATION IS BUILT ON TRANSPARENCY, VERIFIED DOCUMENTATION, AND UNCOMPROMISING FIDELITY.'
  },
  {
    id: 'A03',
    name: 'KABIR SEHGAL',
    role: 'PORTFOLIO STRATEGIST',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400&h=400',
    phone: '+91 98200 54321',
    email: 'kabir.sehgal@saiproperties.com',
    bio: 'KABIR FOCUSES ON STRUCTURING REAL ESTATE INVESTMENTS, PLOT DEVELOPMENT SCHEMES, AND LAND BANK TAX VALUATIONS FOR BOTH INSTITUTIONAL AND ULTRA-HIGH-NET-WORTH INDIVIDUALS.'
  }
];

export const properties: Property[] = [
  {
    id: 'P01',
    title: 'THE MONOLITH PENTHOUSE',
    location: 'KOREGAON PARK, PUNE',
    city: 'PUNE',
    price: 45000000, // 4.5 Cr
    areaSqFt: 4200,
    configuration: '4.5 BHK PENTHOUSE',
    status: 'FOR_SALE',
    type: 'RESIDENTIAL',
    possessionDate: 'READY TO MOVE',
    description: 'AN EXECUTIVE RESIDENCE DEFINED BY BRUTALIST CONCRETE EDGES, DOUBLE-HEIGHT CEILINGS, AND A BREATHTAKING METROPOLITAN PANORAMA. THE APARTMENT FEATURES A SEAMLESS INTEGRATION OF ACTIVE LIGHT WELLS AND CONTINUOUS BORDER PLATES.',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1200&h=800',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&q=80&w=1200&h=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=1200&h=800'
    ],
    highlights: [
      'CENTRALIZED HYBRID HEATING & COOLING',
      '1200 SQ.FT. PRIVATE ASYMMETRIC DECK',
      'VISIBLE EXPOSED STRUCTURAL CONCRETE PILLARS',
      '4 INDEPENDENT SECURE PARKING SLOTS'
    ],
    specifications: {
      'STRUCTURE': 'EXPOSED R.C.C. SHEAR WALLS AND BEAMS CONSTRUCTED WITH GRADE M40 CONCRETE.',
      'FLOORING': 'INTEGRAL POLISHED BASALT PLATES METICULOUSLY ALIGNED TO AN 800MM GRID SYSTEM.',
      'WINDOWS': 'SCHÜCO THERMALLY INSULATED SLIDING PROFILES WITH TRIPLE-GLAZED ARGON-FILLED GLASS PANELS.',
      'ELECTRICAL': 'COMPLETELY CONCEALED COPPER CONDUITS WITH PREMIUM BRANDED MODULAR PLATES AND SMART SWITCHES.',
      'SANITARY': 'MATTE BLACK WALL-HUNG FIXTURES WITH CONCEALED IN-WALL FLUSH SYSTEMS.'
    },
    agentId: 'A02'
  },
  {
    id: 'P02',
    title: 'GRID-A HEADQUARTERS',
    location: 'BANDRA KURLA COMPLEX, MUMBAI',
    city: 'MUMBAI',
    price: 185000000, // 18.5 Cr
    areaSqFt: 8500,
    configuration: 'COMMERCIAL FLOOR',
    status: 'FOR_SALE',
    type: 'COMMERCIAL',
    possessionDate: 'OCTOBER 2026',
    description: 'A FULL-FLOOR STRATEGIC COMMERCIAL HEADQUARTERS ENGINEERED FOR AGILITY AND PRECISION. DESIGNED AROUND A CENTRAL CORE LAYOUT COMPLEMENTED BY AN INTENSE PERIMETER COLUMN GRID AND VISIBLE TECHNICAL CONDUIT SYSTEMS.',
    images: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1200&h=800',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1200&h=800'
    ],
    highlights: [
      'TRIPLE-HEIGHT GRAND ATRIUM ACCESS',
      'VARIABLE REFRIGERANT VOLUME (VRV) AIR CONDITIONING',
      '99.99% POWER BACKUP ACCORDING TO DATA CENTER STANDARDS',
      'EXECUTIVE LOUNGE INTEGRATED WITH DIAGONAL GLASSED FACADE'
    ],
    specifications: {
      'STRUCTURE': 'FLAT SLAB SYSTEM WITH INTEGRATED COFFER CEILING GRID FOR HEAVY LOADING TOLERANCE.',
      'FACADE': 'HIGH-PERFORMANCE LOW-E CURTAIN WALL RATED AT 1.4 W/M²K U-VALUE.',
      'ELEVATORS': 'FOUR HIGH-SPEED PASSENGER LIFTS EQUIPPED WITH DESTINATION CONTROL SYSTEMS.',
      'FIRE SAFETY': 'AUTOMATIC ADVANCED PRE-ACTION WATER SPRINKLERS CONNECTED TO CENTRAL ANNOUNCEMENT PANELS.'
    },
    agentId: 'A01'
  },
  {
    id: 'P03',
    title: 'THE AXIS FLATPLATE',
    location: 'INDIRANAGAR, BANGALORE',
    city: 'BANGALORE',
    price: 280000, // 2.8 Lakh / Month
    areaSqFt: 2900,
    configuration: '3 BHK APARTMENT',
    status: 'FOR_RENT',
    type: 'RENTAL',
    possessionDate: 'IMMEDIATE',
    description: 'A LINEAR THREE-BEDROOM RESIDENCE INTEGRATING SWISS-STYLE STRUCTURAL MINIMALISM WITH LUXURIOUS LIVEABILITY. DESIGNED WITH SHARP RECTANGULAR ZONES, FLOATING STORAGE PLANES, AND EXTREMELY TALL GLASS DOORS.',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1200&h=800',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&q=80&w=1200&h=800'
    ],
    highlights: [
      'MINIMALIST BUILT-IN BOFFI KITCHEN',
      'SEAMLESS HEATED SOLID WOOD FLOORS',
      'INTEGRATED TECHNICAL LIGHTING RAILED GRID',
      'DEDICATED CONCIERGE AND VERIFIED ACCESS PROTOCOL'
    ],
    specifications: {
      'STRUCTURE': 'REINFORCED CONCRETE SHELL WITH BRICKWORK INTERNAL PARTITIONS.',
      'FLOORING': 'NATURAL NATURAL OAK WOOD PLANK FLOORING INSULATED WITH PREMIUM COMPRESSED CORK SHEETS.',
      'LIGHTING': 'MAGNETIC TRACK SYSTEM WITH RECESSED SPOTLIGHTS (3000K, HIGH CRI > 90).',
      'KITCHEN': 'FITTED WITH MIELE OVEN, INDUCTION HOB, AND FULL-HEIGHT CONCEALED REFRIGERATOR SYSTEM.'
    },
    agentId: 'A02'
  },
  {
    id: 'P04',
    title: 'SECTOR-12 INDUSTRIAL PLOT',
    location: 'CHAKAN INDUSTRIAL AREA, PUNE',
    city: 'PUNE',
    price: 120000000, // 12.0 Cr
    areaSqFt: 43560, // 1 Acre
    configuration: 'INDUSTRIAL/LOGISTICS LAND',
    status: 'FOR_SALE',
    type: 'PLOT',
    possessionDate: 'READY FOR CONSTRUCTION',
    description: 'A HIGHLY PRECISE ONE-ACRE FLAT PLOT STRATEGICALLY LOCATED WITH DIRECT SIX-LANE INDUSTRIAL HIGHWAY FEEDERS. BOUNDED BY REINFORCED CONCRETE WALLS AND REGISTERED FOR IMMEDIATE INDUSTRIAL OR WAREHOUSE FABRICATION.',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=1200&h=800'
    ],
    highlights: [
      '100% CLEAR TITLE COMPREHENSIVELY VERIFIED',
      '45-METER FRONTAGE FACING NORTHEAST DIRECTLY',
      'HEAVY INDUSTRIAL POWER CORRIDOR ACCESS',
      'PRE-BUILT HEAVY VEHICLE RAMP GATES'
    ],
    specifications: {
      'ZONING': 'APPROVED FOR HEAVY MACHINERY MANUFACTURING, ASSEMBLY, AND CARGO LOGISTICS HUB.',
      'DRAINAGE': 'PRE-FABRICATED CONCRETE STORMWATER DISCHARGE SYSTEM INTEGRATED TO MAIN CHANNEL.',
      'SECURITY': '6-FEET BRICK REINFORCED PERIMETER WALL COMPLEMENTED BY STEEL CONCERTINA TOP WIRES.'
    },
    agentId: 'A03'
  },
  {
    id: 'P05',
    title: 'THE LINEAR LOFT',
    location: 'WORLI SEA FACE, MUMBAI',
    city: 'MUMBAI',
    price: 32000000, // 3.2 Cr
    areaSqFt: 1850,
    configuration: '2 BHK RESIDENCE',
    status: 'SOLD',
    type: 'RESIDENTIAL',
    possessionDate: 'COMPLETED',
    description: 'A TYPOGRAPHICAL RE-IMAGINATION OF COASTAL LIVING. AN ASYMMETRIC APARTMENT THAT PRIORITIZES COMPACT RECTANGULAR VOLUMES, FLOATING INTERNAL ROOM DIVIDERS, AND EXTREME HIGH-FREQUENCY STRUCTURAL GLAZING TOWARDS THE ARABIAN SEA.',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=1200&h=800'
    ],
    highlights: [
      'FULL-HEIGHT SEA FACING GLAZING',
      'RAW BRUTALIST EXPOSED CEILINGS WITH DUCTS',
      'MINIMALIST SEAMLESS STORAGE WALLS',
      'ELEVATED PRIVATE STUDY WITH COMPACT STACKING'
    ],
    specifications: {
      'STRUCTURE': 'FRAME STRUCTURE WITH EXPOSED TEXTURED BEAMS AND CEILING CASTING LINES.',
      'FLOORING': 'GREY INDUSTRIAL FLOOR COATING COVERED WITH TRANSPARENT ACRYLIC CONDUIT PIPES.',
      'AIR QUALITY': 'CONTINUOUS AIR RECIRCULATION SYSTEM EQUIPPED WITH MEDICAL-GRADE HEPA FILTRATION.'
    },
    agentId: 'A01'
  },
  {
    id: 'P06',
    title: 'MODULOR COMMERCIAL BLOCK',
    location: 'WHITEFIELD, BANGALORE',
    city: 'BANGALORE',
    price: 1250000, // 12.5 Lakh / Month
    areaSqFt: 14000,
    configuration: 'COMMERCIAL LAB / OFFICE',
    status: 'FOR_RENT',
    type: 'RENTAL',
    possessionDate: 'AUGUST 2026',
    description: 'NAMED IN HOMAGE TO LE CORBUSIER’S ANTHROPOMETRIC SCALE, THE MODULOR BLOCK PROVIDES 14,000 SQ.FT. OF STRATEGICALLY SUBDIVIDED RESEARCH, LAB, OR CORPORATE WORKSPACE FEATURING INTEGRAL FLAT FLOORPLATES.',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1200&h=800'
    ],
    highlights: [
      'MEETS STRUCTURAL RATING FOR BIOLAB LOAD CAPABILITY',
      'SEAMLESS 4-WAY FLOOR INTEGRATION PORTS',
      'HEAVY CARGO HOIST LIFTS INTEGRATED',
      'RESTRICTED ACCESSIBLE BIOMETRIC SECURE ZONES'
    ],
    specifications: {
      'HVAC': 'SEPARATE SECTOR VENTILATION WITH COMPACT DAMPERS TO PREVENT CROSS-CONTAMINATION.',
      'LOADING': 'DESIGNED FOR AN AXIAL WEIGHT CAPACITY OF UP TO 1000 KG PER SQUARE METER.',
      'BACKUP': '2X DEDICATED CUMMINS GENERATOR SETS WITH SEAMLESS 8-MILLISECOND COLD RECOVERY TRANSITION.'
    },
    agentId: 'A03'
  }
];

export const journalPosts: JournalPost[] = [
  {
    id: 'J01',
    title: 'THE GEOMETRY OF PERMANENCE: THE REAL ESTATE AS AN ARCHITECTURAL ARTIFACT',
    category: 'ESSAY',
    date: '2026-05-14',
    summary: 'AN EXAMINATION OF HOW STARK GEOMETRICAL FORMS AND EXPOSED STRUCTURAL SYSTEMS COMMAND LONG-TERM CAPITAL VALUE PRESERVATION IN INFLATIONARY ECONOMIES.',
    content: 'REAL ESTATE IS NOT MERELY A TRANSACTIONAL ENTITY BUT A PHYSICAL EXPRESSION OF STRUCTURE. HISTORICALLY, THE BUILDINGS THAT COMMAND THE MOST RESILIENT CAPITAL PRESERVATION ARE THOSE CONSTRUCTED WITH MATHEMATICAL RIGOR AND STRUCTURAL INTEGRITY. IN THIS ESSAY, WE DEMYSTIFY THE RELATIONSHIP BETWEEN STARK MODERNIST ARCHITECTURE, OBJECTIVE SPATIAL UTILITY, AND TRANSACTIONAL VALUE RETENTION...',
    readTime: '6 MIN'
  },
  {
    id: 'J02',
    title: 'VERIFIED METRICS: ELIMINATING EMOTIONAL CLICHÉS IN LUXURY TRANSACTIONS',
    category: 'STRATEGY',
    date: '2026-06-02',
    summary: 'WHY DISCIPLINED DATA-FORWARD TRANSACTION METRICS PROVIDE FAR SUPERIOR OUTCOMES FOR HIGH-NET-WORTH FAMILY OFFICES COMPARED TO EMOTIONAL MARKETING CAMPAIGNS.',
    content: 'THE LUXURY REAL ESTATE SECTOR HAS HISTORICALLY SUFFERED FROM ADJECTIVAL OVERLOAD—"MAGNIFICENT VIEW," "STUNNING RETREAT," "OPULENT RESIDENCE." COMPREHENSIVELY REJECTING THESE SUBJECTIVE CLICHÉS, WE ADVOCATE FOR AN ANALYTICAL TRADING PROTOCOL THAT QUANTIFIES COMPONENT SPECIFICATIONS, THERMAL MASS RATINGS, CLEAR GRID MEASUREMENTS, AND VERIFIED LEGAL REGISTRY HISTORY...',
    readTime: '4 MIN'
  },
  {
    id: 'J03',
    title: 'THE MODULOR AND METROPOLITAN PUNE: A DENSITY SPECIFICATION STUDY',
    category: 'RESEARCH',
    date: '2026-06-25',
    summary: 'A GEOMETRIC AND SPATIAL ANALYSIS OF URBAN INTENSITY IN KOREGAON PARK AND THE RISE OF THE EXPOSED REINFORCED CONCRETE RESIDENCE.',
    content: 'AS CORE URBAN CENTERS NAVIGATE SPATIAL DEPLETION, THE APPLICATION OF MULTI-LEVEL FLAT RESIDENCES DEMANDS EXTREME LAYOUT EFFICIENCY. THROUGH A SERIES OF GRAPHIC RECONSTRUCTIONS AND NUMERICAL FORMULATIONS, WE MAP THE ECONOMIC DENSITIES OF LAND USE PATTERNS AND ASSESS THE LONG-TERM UTILITY PROFILES OF RECTANGULAR VERSUS RADIAL INTERIOR FLOORPLAN GEOMETRIES...',
    readTime: '8 MIN'
  }
];

export const testimonials: Testimonial[] = [
  {
    id: 'T01',
    name: 'DR. ARNAV SEN',
    role: 'FOUNDER & CHIEF NEUROSURGEON',
    company: 'SEN NEUROLOGY CLINIC',
    quote: 'SAI PROPERTIES REJECTED EVERY STANDARD AGENT CLICHÉ. THEY SPOKE ENTIRELY IN VERIFIED STRUCTURAL NUMBERS, ENERGY EFFICIENCY METRICS, AND CLEAR PROPERTY TITLES. MY PURCHASE OF THE MONOLITH APARTMENT WAS TRANSACTED LIKE A PRECISE SURGICAL OPERATION.',
    date: 'APRIL 2026'
  },
  {
    id: 'T02',
    name: 'MEERA SHAH',
    role: 'MANAGING PARTNER',
    company: 'CHRONOS CAPITAL VENTURES',
    quote: 'IN LUXURY TRANSACTIONS, TIME IS THE CHIEF SCARCITY. SAI PROPERTIES FACILITATED COLD-EYED LEGAL DUE DILIGENCE, CLEAR GRIDS, AND STRUCTURAL AUDITS PRIOR TO OUR FIRST VISIT. A HIGHLY IMPRESSIVE EXECUTION OF OBJECTIVE VALUE STRUCTURE.',
    date: 'MAY 2026'
  }
];

export const faqs: FAQItem[] = [
  {
    id: 'F01',
    question: 'HOW ARE LAND GRIDS AND STRUCTURAL AREA CALCULATIONS VERIFIED?',
    answer: 'EVERY PROPERTY IN THE SAI PROPERTIES PORTFOLIO UNDERGOES THREE-POINT STRUCTURAL AUDITING. CARPET AREAS ARE MEASURED ACCORDING TO REAL ESTATE REGULATORY AUTHORITY STANDARDS AND ARE SCIENTIFICALLY RE-VERIFIED BY AN INDEPENDENT CIVIL ENGINEERING FIRM PRIOR TO COMPILING THE LISTING DATA.'
  },
  {
    id: 'F02',
    question: 'WHY DOES SAI PROPERTIES REJECT "EMOTIONAL BRANDING" IN ITS LISTINGS?',
    answer: 'WE BELIEVE REAL ESTATE INVESTMENT IS AN OBJECTIVE DECISION. SUBJECTIVE SLOGANS AND STAGED PHOTOGRAPHY MASK STRUCTURAL REALITIES. BY PROVIDING STRICT DATA SHEETS, THERMAL INSULATION COEFFICIENTS, CONCRETE GRADES, AND HIGH-CONTRAST IMAGERY, WE EQUIP BUYERS WITH UNVARNISHED FACTUAL FIDELITY.'
  },
  {
    id: 'F03',
    question: 'WHAT IS THE TYPICAL CLOSURE TIMELINE FOR HIGH-VALUE COMMERCIAL LEASES?',
    answer: 'DUE TO THE COMPLETENESS OF OUR READY-TO-DRAFT TITLE CERTIFICATES AND REGULATORY APPROVAL FOLDERS, TYPICAL CLOSURE TIMELINES ARE CONDENSED FROM 90 DAYS TO 18 BUSINESS DAYS, ENSURING EXTREMELY LOW TRANSACTION FRICTION.'
  }
];

export const milestones: Milestone[] = [
  {
    year: '2011',
    title: 'GRID FOUNDATION',
    description: 'ESTABLISHED IN PUNE WITH A STRICT DIRECTIVE TO ENGAGE ONLY IN DIRECTLY-SOURCED, 100% CLEAR TITLE LAND TRANSACTION PLOTS.'
  },
  {
    year: '2016',
    title: 'METROPOLITAN XPANSION',
    description: 'OFFICIALLY EXPANDED SERVICES TO MUMBAI AND BANGALORE, STRUCTURING ASYMMETRIC FLATS AND CORPORATE HEADQUARTERS IN CORE CBD BUSINESS DISTRICTS.'
  },
  {
    year: '2021',
    title: 'THE BRUTALIST AUDIT STANDARD',
    description: 'INTRODUCED COLD-FACT PHYSICAL SPECIFICATION METRICS FOR ALL HOUSING LISTINGS, CREATING A STANDARD UNRIVALED IN WESTERN INDIA REAL ESTATE.'
  },
  {
    year: '2025',
    title: '₹2,500 CR IN VERIFIED VOLUMES',
    description: 'SURPASSED A CUMULATIVE TRANSACTION THRESHOLD OF ₹25 BILLION ACROSS RESIDENTIAL, COMMERCIAL, AND INDUSTRIAL LAND PORTFOLIOS.'
  }
];

export const stats: StatsBlock[] = [
  { label: 'PROPERTIES TRANSACTED', value: '450', prefix: '+' },
  { label: 'CITIES COVERED', value: '3', prefix: '' },
  { label: 'YEARS ACTIVE IN MARKET', value: '15', prefix: '+' },
  { label: 'VERIFICATION RATING', value: '100', prefix: '%' }
];
